version: '3'

services:
  app:
    container_name: app_py
    build:
       context: ../
       dockerfile: ./docker/dockerfiles/aps.dockerfile
    env_file:
      - .env
    expose:
      - 5000
    networks:
      - custom_network_1
    ports:
      - 5000:5000
  bot:
    container_name: bot_py
    build:
       context: ../
       dockerfile: ./docker/dockerfiles/bot.dockerfile
    env_file:
      - .env
    networks:
      - custom_network_1
    


  
networks:
   custom_network_1:
     
      

